version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: needly-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - needly-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: needly-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3001:3000"
    networks:
      - needly-network
    restart: unless-stopped

volumes:
  grafana_data:

networks:
  needly-network:
    external: true
